BASIC operations

In [84]:
import numpy as np
a = np.array([5,6,9,2,4])
a.ndim

1

In [85]:
a = np.array([[5,6,9,2,4],[3,4,5,5,2],[6,6,7,0,2]])
a.ndim

2

In [86]:
a.itemsize

4

In [87]:
a.dtype

dtype('int32')

In [88]:
a= np.array([[5,6,9,2,4],[3,4,5,5,2],[6,6,7,0,2]], dtype=np.float64)
a.itemsize

8

In [89]:
a.size

15

In [90]:
a.shape

(3, 5)

In [91]:
#creating an array and setting the datatype of elements to complex
a= np.array([[5,6,9,2,4],[3,4,5,5,2],[6,6,7,0,2]], dtype = complex) 
a

array([[5.+0.j, 6.+0.j, 9.+0.j, 2.+0.j, 4.+0.j],
       [3.+0.j, 4.+0.j, 5.+0.j, 5.+0.j, 2.+0.j],
       [6.+0.j, 6.+0.j, 7.+0.j, 0.+0.j, 2.+0.j]])

In [92]:
#creating a zero valued array
np.zeros( (3,3),dtype=complex )

array([[0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j]])

In [93]:
a=np.arange(4,100)
a

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
       55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
       72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88,
       89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [94]:
#creates array in range 1 to 100 with gap of 4
np.arange(1,100,4)

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [95]:
#creates array between 1 to 5 containing 10 elements
a=np.linspace(1,5,10)
a

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [96]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
a.shape

(2, 3)

In [98]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [99]:
#reshape the array 
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [102]:
#flattening the array -> 1-D
a.ravel()#on;y returs no modifictaion

array([1, 2, 3, 4, 5, 6])

In [101]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
#mathematics thoda 
a.min()

1

In [104]:
a.max()

6

In [105]:
a.mean()

3.5

In [110]:
a.sum(axis=1)#doubt in axis->vertical

array([ 6, 15])

In [117]:
print(a.sum(axis=0))#horizontal
print("Meow")
print(a)

[5 7 9]
Meow
[[1 2 3]
 [4 5 6]]


In [122]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [123]:
np.std(a)

1.707825127659933

In [124]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [127]:
print(a+b)
print("----")
print(a-b)
print("----")
print(a*b)
print("----")
print(a/b)

[[ 6  8]
 [10 12]]
----
[[-4 -4]
 [-4 -4]]
----
[[ 5 12]
 [21 32]]
----
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [128]:
a.dot(b)

array([[19, 22],
       [43, 50]])