INDEXING AND SLICING AND STACKING

In [10]:
import numpy as np

In [11]:
a = [6,7,8]
a[-1]

8

In [12]:
a = np.array([6,7,8])
a[0:2]

array([6, 7])

In [13]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a[1,2]

6

In [15]:
a[1:3,2]

array([6, 9])

In [16]:
a[-1]

array([7, 8, 9])

In [17]:
for row in a:
    print(row)

    

[1 2 3]
[4 5 6]
[7 8 9]


In [18]:
for cell in a.flat:{
    print (cell)
}

1
2
3
4
5
6
7
8
9


In [19]:
a = np.arange(6).reshape(3,2)

In [21]:
b = np.arange(6,12).reshape(3,2)

In [22]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [23]:
b


array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [24]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [25]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [31]:
a = np.arange(30).reshape(2,15)

In [32]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [33]:
result = np.hsplit(a,3)
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [34]:
result = np.vsplit(a,2)

In [35]:
result

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [36]:
a = np.arange(12).reshape(3,4)

In [37]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
b = a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [42]:
a[b]
#extarct 

array([ 5,  6,  7,  8,  9, 10, 11])

In [43]:
a[b]=-1

In [44]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])