In [2]:
import numpy as np

In [3]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [10]:
for x in np.nditer(a,order='C'):
    print (x)

0
1
2
3
4
5
6
7
8
9
10
11


In [12]:
for x in np.nditer(a,order='F',flags=['external_loop']):
    print (x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [13]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x*x

In [14]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [30]:
b = np.arange(3,15,5).reshape(3,1)
b

array([[ 3],
       [ 8],
       [13]])

In [31]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 8
25 8
36 8
49 8
64 13
81 13
100 13
121 13
